### ISSUE TITLE
Commit Lint format 

### ISSUE THREAD

**Issue by SidV2** [tomalaforge/angular-challenges#944]
The documentation should match the commit message format expected while committing. 

The documentation states commit message format like "Answer: 34" but users cannot commit with that format.

I had to use feat: answer 34 to commit which does not match the documentation.

<img width="962" alt="Screenshot 2024-05-21 at 2 05 10 PM" src="https://github.com/tomalaforge/angular-challenges/assets/17374208/c10f9433-602e-4090-953d-8b35867eb06e">

**Comment by tomalaforge** [comment]
Yes, I understand it's a bit misleading, but the commit message and the PR title are two separate things. 

I added the conventional commit convention because most OSS projects use this convention and this project has been made to also learn how to contribute to OSS. 

But you need to update the title of your PR when you push it to the repo. 

Does it make sense ?

**Comment by SidV2** [comment]
Hello,

Yeah that makes sense. I will close the issue.
